apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: sample-deployment
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
