apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  externalIPs:
    - 10.96.0.10
    - 10.96.0.11
  ports:
    - name: "http-port"
      port: 8080
      protocol: "TCP"
      targetPort: 80
  selector:
    app: sample-app
