apiVersion: v1
kind: Pod
metadata:
  name: sample-kubectl
spec:
  containers:
    - name: kubectl-container
      image: lachlanevenson/k8s-kubectl:v1.10.4
      command:
        - sleep
        - "86400"
